In [18]:
import sys; sys.path.append('../Preprocess/');
from preprocess import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, make_scorer
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [11]:
df = pd.read_csv('../Dataset/body_level_classification_train.csv')

In [12]:
df_p = preprocess(df, resample_=True)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df_p.iloc[:, :-1], df_p.iloc[:, -1], test_size=0.2, random_state=0)

In [14]:
scorer = make_scorer(f1_score, average='weighted')

In [6]:
!mkdir Results/

The syntax of the command is incorrect.


In [ ]:
# GridSearch
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# SVM
param_grid = {'C': [0.1, 1, 3, 5, 7, 10, 12, 14, 15],
                'gamma': [4, 2, 1, 0.1, 0.01, 0.001, 0.0001],
                'kernel': ['rbf', 'poly', 'sigmoid', 'linear']}

grid = GridSearchCV(SVC(), param_grid, refit=True, cv=5, scoring=scorer)
grid.fit(X_train, y_train)
# output the cv result to csv
pd.DataFrame(grid.cv_results_).to_csv('Results/svm_grid_search_cv.csv')


In [ ]:

print(grid.best_params_)
print(grid.best_estimator_)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions, digits=4))
print(confusion_matrix(y_test, grid_predictions))      
# print f1 score
# print(f1_score(y_test, grid_predictions, average='weighted'))        

{'C': 15, 'gamma': 4, 'kernel': 'linear'}
SVC(C=15, gamma=4, kernel='linear')
              precision    recall  f1-score   support

           1       0.98      1.00      0.99       132
           2       0.99      0.97      0.98       138
           3       0.99      0.98      0.99       125
           4       0.99      1.00      1.00       149

    accuracy                           0.99       544
   macro avg       0.99      0.99      0.99       544
weighted avg       0.99      0.99      0.99       544

[[132   0   0   0]
 [  3 134   1   0]
 [  0   1 123   1]
 [  0   0   0 149]]
0.9889430690248693


In [ ]:
# Random Forest
param_grid = {'n_estimators': [10, 50, 100, 200, 500],
                'max_features': ['sqrt', 'log2'],
                'max_depth' : [4,5,6,7,8, 12, 16],
                'criterion' :['gini', 'entropy']}
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, cv=5, scoring=scorer)
grid.fit(X_train, y_train)
# output cv results to csv
pd.DataFrame(grid.cv_results_).to_csv( 'Results/random_forest_grid_search_results.csv')

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
print(grid.best_estimator_)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions, digits=4))
print(confusion_matrix(y_test, grid_predictions))
# print(f1_score(y_test, grid_predictions, average='weighted'))

{'criterion': 'entropy', 'max_depth': 12, 'max_features': 'log2', 'n_estimators': 200}
RandomForestClassifier(criterion='entropy', max_depth=12, max_features='log2',
                       n_estimators=200)
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       132
           2       0.99      0.99      0.99       138
           3       0.98      0.98      0.98       125
           4       0.99      0.99      0.99       149

    accuracy                           0.99       544
   macro avg       0.99      0.99      0.99       544
weighted avg       0.99      0.99      0.99       544

[[132   0   0   0]
 [  0 136   2   0]
 [  0   2 122   1]
 [  0   0   1 148]]
0.9889705882352942


In [ ]:
{'criterion': 'entropy', 'max_depth': 12, 'max_features': 'sqrt', 'n_estimators': 100}
clf = RandomForestClassifier(criterion='entropy', max_depth=12, max_features='sqrt', n_estimators=100)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

print(classification_report(y_test, predictions, digits=4))
print(confusion_matrix(y_test, predictions))
# print f1 score
# print(f1_score(y_test, predictions, average='weighted'))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       132
           2       1.00      0.99      0.99       138
           3       0.98      0.98      0.98       125
           4       0.99      0.99      0.99       149

    accuracy                           0.99       544
   macro avg       0.99      0.99      0.99       544
weighted avg       0.99      0.99      0.99       544

[[132   0   0   0]
 [  0 136   2   0]
 [  0   0 123   2]
 [  0   0   1 148]]
0.9908229367862087


# No Resampling

In [21]:
df_p = preprocess(df, resample_=False)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(df_p.iloc[:, :-1], df_p.iloc[:, -1], test_size=0.2, random_state=0)

In [20]:
scorer = make_scorer(f1_score, average='weighted')

In [ ]:
!mkdir Results/

mkdir: cannot create directory ‘Results/’: File exists


In [ ]:
# GridSearch
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# SVM
param_grid = {'C': [0.1, 1, 3, 5, 7, 10, 12, 14, 15],
                'gamma': [4, 2, 1, 0.1, 0.01, 0.001, 0.0001],
                'kernel': ['rbf', 'poly', 'sigmoid', 'linear']}

grid = GridSearchCV(SVC(), param_grid, refit=True, cv=5, scoring=scorer)
grid.fit(X_train, y_train)
# output the cv result to csv
pd.DataFrame(grid.cv_results_).to_csv('Results/svm_grid_search_cv.csv')


In [ ]:

print(grid.best_params_)
print(grid.best_estimator_)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions, digits=4))
print(confusion_matrix(y_test, grid_predictions))      
# print f1 score
# print(f1_score(y_test, grid_predictions, average='weighted'))        


{'C': 10, 'gamma': 4, 'kernel': 'linear'}
SVC(C=10, gamma=4, kernel='linear')
              precision    recall  f1-score   support

           1       0.98      1.00      0.99        40
           2       1.00      0.98      0.99        41
           3       0.98      1.00      0.99        87
           4       1.00      0.98      0.99       128

    accuracy                           0.99       296
   macro avg       0.99      0.99      0.99       296
weighted avg       0.99      0.99      0.99       296

[[ 40   0   0   0]
 [  1  40   0   0]
 [  0   0  87   0]
 [  0   0   2 126]]
0.9898766541237013


In [ ]:
# Random Forest
param_grid = {'n_estimators': [10, 50, 100, 200, 500],
                'max_features': ['sqrt', 'log2'],
                'max_depth' : [4,5,6,7,8, 12, 16],
                'criterion' :['gini', 'entropy']}
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, cv=5, scoring=scorer)
grid.fit(X_train, y_train)
# output cv results to csv
pd.DataFrame(grid.cv_results_).to_csv( 'Results/random_forest_grid_search_results.csv')

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
print(grid.best_estimator_)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions, digits=4))
print(confusion_matrix(y_test, grid_predictions))
# print f1 score
# print(f1_score(y_test, grid_predictions, average='weighted'))


{'criterion': 'entropy', 'max_depth': 12, 'max_features': 'log2', 'n_estimators': 200}
RandomForestClassifier(criterion='entropy', max_depth=12, max_features='log2',
                       n_estimators=200)
              precision    recall  f1-score   support

           1       1.00      0.97      0.99        40
           2       0.90      0.90      0.90        41
           3       0.93      0.94      0.94        87
           4       0.98      0.98      0.98       128

    accuracy                           0.96       296
   macro avg       0.95      0.95      0.95       296
weighted avg       0.96      0.96      0.96       296

[[ 39   1   0   0]
 [  0  37   4   0]
 [  0   2  82   3]
 [  0   1   2 125]]
0.9561658765456235


In [ ]:
# LightGBM
param_grid = {
    # 'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'learning_rate': [0.05, 0.1, 0.2, .3, .5],
    # 'n_estimators': [50, 100, 200, 500],
    'n_estimators': [100, 500, 1000],
    # 'num_leaves': [4, 8, 16, 32, 64],
    # 'num_leaves': [32, 64],
    # 'max_depth': [4, 5, 6, 7, 8, 12, 16],
    # 'max_depth': [12, 16],
    'boosting_type' : ['gbdt', 'dart', 'goss'],
    'objective' : ['multiclass'],
    # 'random_state' : [501],
    # 'colsample_bytree' : [0.65, 0.66],
    # 'subsample' : [0.7,0.75],
    # 'reg_alpha' : [0.001, 1, 2.0],
    # 'reg_lambda' : [0.001, 1, 2.0],
}
grid = GridSearchCV(LGBMClassifier(), param_grid, refit=True, cv=5, scoring=scorer)
grid.fit(X_train, y_train)
# output cv results to csv
pd.DataFrame(grid.cv_results_).to_csv( 'Results/lightGBM_grid_search_results.csv')

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
print(grid.best_estimator_)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions, digits=4))
print(confusion_matrix(y_test, grid_predictions))
# print f1 score
# print(f1_score(y_test, grid_predictions, average='weighted'))


In [23]:
# XGBoost
param_grid = {
    # 'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'learning_rate': [0.05, 0.1, 0.2, .3],
    # 'n_estimators': [10, 50, 100, 200, 500],
    'n_estimators': [100, 1000],
    # 'max_depth': [4, 5, 6, 7, 8, 12, 16],
    # 'max_depth': [4, 8, 12, 16],
    # 'booster' : ['gbtree', 'gblinear', 'dart'],
    'objective' : ['multi:softmax'],
    # 'random_state' : [501], # Updated from 'seed'
    # 'colsample_bytree' : [0.65, 0.66],
    # 'subsample' : [0.7,0.75],
    'reg_alpha' : [.1, 1,1.2, 2],
    'reg_lambda' : [.1, 1,1.2,1.4, 2],
}

grid = GridSearchCV(XGBClassifier(), param_grid, refit=True, cv=5, scoring=scorer)
grid.fit(X_train, y_train)
# output cv results to csv
pd.DataFrame(grid.cv_results_).to_csv( 'Results/XGBoost_grid_search_results.csv')

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None,
                                     num_parallel_tree=None, predictor=None,
                                     random_state=None, ...),
             param_grid={'learning_rate': [0.05, 0.1, 0.2, 0.3],
                         'n_estimators': [100, 1000],
                         'objective': ['multi:softmax'],
                         'reg_alpha': [0.1, 1, 1.2, 2],
                         'reg_lambda': [0.1, 1, 1.2, 1.4, 2]},
             scoring=make_scorer(f1_score, average=weighted))

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
print(grid.best_estimator_)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions, digits=4))
print(confusion_matrix(y_test, grid_predictions))
# print f1 score
# print(f1_score(y_test, grid_predictions, average='weighted'))


{'learning_rate': 0.2, 'n_estimators': 1000, 'objective': 'multi:softmax', 'reg_alpha': 0.1, 'reg_lambda': 1}
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=None, num_parallel_tree=None,
              objective='multi:softmax', predictor=None, ...)
              precision    recall  f1-score   support

           0     0.9750    0.9750    0.9750        40
           1     0.92